### ISSUE TITLE
Доработать алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [Hurin97/test_task#1]
Добрый день, меня зовут Вадим, я представитель компании Uno-Soft.

По файлу https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-4.txt.gz не выполнено условие в 30 секунд. Поправьте этот момент пожалуйста.

**Comment by Hurin97** [comment]
Добрый день, Вадим!
У меня при запуске по строке:  java -Xmx1G -jar someartid-1.0-SNAPSHOT.jar M:/lng.txt M:/u.txt
![image](https://github.com/Hurin97/test_task/assets/56901405/fbca623f-8a39-45ef-9d67-71a4d94b0988)
и условие выполняется при подаче данного файла без изменений в коде.

**Comment by Kasiwadzaki** [comment]
@Hurin97 Прошу прощения, моя оплошность, были проблемы с Intellij при проверку на jar все хорошо.
